from enum import Enum


class ReportType(str, Enum):
    GET_FLAT_FILE_ORDER_REPORT_DATA = '_GET_FLAT_FILE_ORDER_REPORT_DATA_'
    GET_FLAT_FILE_ACTIONABLE_ORDER_DATA = '_GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_'
    GET_AMAZON_FULFILLED_SHIPMENTS_DATA = '_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_'
    GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA = '_GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA_'
    GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA = '_GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA_'
    GET_MERCHANT_LISTINGS_DATA = '_GET_MERCHANT_LISTINGS_DATA_'
    GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 = '_GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2_'
    GET_SELLER_FEEDBACK_DATA = '_GET_SELLER_FEEDBACK_DATA_'
    GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA = '_GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA_'
    GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA = '_GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA_'
